# Generated by Django 5.2.4 on 2025-07-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.FloatField(default=0.0, verbose_name='Score'),
        ),
    ]
