# Generated by Django 5.2.4 on 2025-07-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_answer_image_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(default=10, help_text='Durasi dalam menit'),
        ),
    ]
