# Generated by Django 5.2.4 on 2025-07-30 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_remove_quiz_duration_quiz_duration_minutes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='takenquiz',
            unique_together={('student', 'quiz')},
        ),
    ]
